In [5]:
import numpy as np

In [6]:
vec = np.array([[1,2], [3,4], [5,6]])

In [7]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
vec.dtype

dtype('int64')

In [9]:
type(vec)

numpy.ndarray

In [10]:
vec.shape

(3, 2)

In [11]:
vec.ndim

2

In [12]:
np.sum(vec)

21

In [13]:
np.sum(vec, axis=0)

array([ 9, 12])

In [14]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [15]:
vec.sum()

21

In [16]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [17]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [18]:
vec.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
vec.reshape(2, -1)
#-1 значит, что сам подберет значение

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
vec[:, 1]

array([2, 4, 6])

In [26]:
vec[2, :]

array([5, 6])

In [30]:
vec[1:2, 0]

array([3])

In [31]:
vec[1, 0]

3

In [33]:
vec[1:2, 0:1]

array([[3]])

In [35]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

In [36]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [37]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [38]:
vec ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [39]:
vec + vec ** 2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [40]:
vec * vec ** 2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [41]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

In [42]:
vec.dot(vec.T ** 2)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [44]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [47]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

In [48]:
is_even = vec % 2 == 0

In [49]:
is_even

array([[False,  True],
       [False,  True],
       [False,  True]])

In [50]:
np.sum(is_even)

3

In [54]:
vec[vec%2 == 0]
# ответ всегда одномерный

array([2, 4, 6])

In [56]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [58]:
np.ones((2,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1]])

In [59]:
np.ones((2,3), dtype = int).dtype

dtype('int64')

In [60]:
np.ones((2,3), dtype = "int16").dtype

dtype('int16')

In [61]:
np.ones((2,3), dtype = "int16")

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [62]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [66]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [71]:
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [68]:
np.random.rand(2, 3)

array([[0.13569261, 0.15255769, 0.50850233],
       [0.29414765, 0.10099232, 0.19548782]])

In [69]:
np.random.seed(2019)

In [74]:
np.random.rand(2,3)

array([[0.20112905, 0.88601087, 0.51361992],
       [0.57830159, 0.29928265, 0.8371974 ]])

In [77]:
np.random.seed(2019)
np.random.rand(2,3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [78]:
np.random.normal

<function RandomState.normal>

In [82]:
np.random.normal(2, 1, size = 3)
# норм распределние среднее 0 отклонение 1

array([1.65505729, 2.0169049 , 1.48501648])

In [83]:
np.random.randn(2, 1)
#среднее 2, отклонение 1

array([[ 0.24450929],
       [-0.18931261]])

--------------- Задания

In [97]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr[::-1]

array([6, 5, 4, 3, 2, 1])

In [94]:
print(max(arr[arr % 2 == 1]))

5


In [96]:
arr[arr % 2 == 1] = -1
arr

array([-1,  2, -1,  4, -1,  6])

In [105]:
n = 5
arr2 = np.arange(2*n)
arr2 = arr2[arr2 % 2 == 1]
arr2[::-1]

array([9, 7, 5, 3, 1])

In [109]:
a = np.array([0, 1, 2, 3, 4])
num = 1.33
a2 = a - num
print(a[np.argmin(abs(a2))], a[np.argmax(abs(a2))])


1 4
